### ISSUE TITLE
新版 (0.5.0) 下无法在模板中保存 自制/转载 选项

### ISSUE THREAD

**Issue by DCxDESIGN** [biliup/biliup-app#115]
即使在模板中选择了“转载”并保存了模板，下次切换到该模板时依然会默认选中“自制”，与过往版本表现不符

**Comment by DCxDESIGN** [comment]
看了下 config 文件，无论选择什么，copyright 值都是 1，过往版本中，如果选择了转载，该值会变为 2

**Comment by 1toldyou** [comment]
0.5.1已修复
